use caddy as entrypoint instead of traefik
swisstxt/stxt-auth pull request #2
Opened 2024-07-20 11:34 UTC by roosnic1

This PR replaces traefik with caddy. This way a local edit of the `hosts` file is not necessary any more. The [SILAS](https://github.com/swisstxt/sign-language-service) project uses the same. I shamelessly stole the setup from @RudolfSchreier. I also did a minor cleanup in the first commit. You only need to review the changes in the second commit `92376d7fa2306f868fde75eaaef497b4f56cda7c`.

2024-07-23 12:25 UTC, RudolfSchreier requested changes

2024-07-23 12:25 UTC, RudolfSchreier commented on README.md
> +3. Run the setup script `run npm setup`
Should be `npm run setup`, right?

2024-07-23 12:25 UTC, RudolfSchreier commented on README.md
> +2. Run caddy `caddy run`
I know this is legal markdown, but don't you want to start the numbered list at `1.`? 😆

2024-07-23 12:25 UTC, RudolfSchreier commented on README.md
> +- Node
Do we actually need to use `node` on the host for anything?

AFAICT all we are using it for is to call `npm run setup` which just calls a shell script. Why not just call the shell script?

2024-07-23 12:25 UTC, RudolfSchreier commented on README.md
> +- A user from Active Directory in the realm is not visible until they log in for the first time. This means that it's impossible to assign the user to a specific group in advance. Initially, they see
There is still a bit of 🗑️ left at the end of this line (`# keycloak-with-socket-factory`).

2024-07-23 12:25 UTC, RudolfSchreier commented on docker-compose.yml
> +    image: caddy:2.7.5-alpine
The current version is `2.8.6-alpine`, could you try if we can use that one?

2024-07-23 12:25 UTC, RudolfSchreier commented on package.json
> +  "name": "keycloak-with-socket-factory",
(see other comment if we even need `node`)

If this `package.json` sticks around, the name of the project should also be replaced here 🙂.

2024-07-23 12:25 UTC, RudolfSchreier commented on setup/docker-compose.setup.yml
> +    image: caddy:2.7.5-alpine
(see above regarding Caddy version)

2024-07-23 12:25 UTC, RudolfSchreier commented on src/login/client/src/App.js
> +                <li><a href="https://app1.stxt-auth.localhost">App1</a></li>
Just for my curiosity (no change necessary):

Having often encountered HTTP(s) browser fuckery, I tend to always use href attribute values like `"//app1.stxt-auth.localhost"` now.

IIRC this semantically means "please stay on whichever protocol you are already currently using", so should still work.

Would that make sense here?

2024-07-23 14:34 UTC, roosnic1 commented on README.md
> +- Node
Currently we don't use it but in my experience the IDE is happier if node and node_modules exist once a package.json exists. Also i'm pretty sure that we have more scripts in the future to run.

2024-07-23 14:37 UTC, roosnic1 commented on docker-compose.yml
> +    image: caddy:2.7.5-alpine
I guess you meant `2.8.4-apline`?

2024-07-23 14:39 UTC, roosnic1 commented on src/login/client/src/App.js
> +                <li><a href="https://app1.stxt-auth.localhost">App1</a></li>
Absolutely. I'll change this in the other open PR #3 because i moved there the files.

2024-07-24 06:49 UTC, RudolfSchreier commented on docker-compose.yml
> +    image: caddy:2.7.5-alpine
Oh whoops, yep, misread that. `2.8.4-alpine`. 👍

2024-07-25 07:30 UTC, OanaNst approved these changes
Had a look and have no further questions 🍀

2024-07-25 09:48 UTC, devnoname120 reviewed
The general approach is great 👌
I made some comments about browser compatibility and security.

2024-07-25 09:48 UTC, devnoname120 commented on README.md
> +3. Select `Allow all cookies` or `Allow third-party cookies`
Note that third-party cookies are being disabled by default in all majors browsers:
- Chrome: https://developers.google.com/privacy-sandbox/3pcd/prepare/prepare-for-phaseout
- Firefox: https://developer.mozilla.org/en-US/blog/goodbye-third-party-cookies/
- Safari: https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

So as far as I understand we can't rely on them in the future as is without modifications. 

There seems to be some heuristics and workarounds (such as [Related Website Sets](https://github.com/WICG/first-party-sets)) to make it work but I'm not knowledgeable about this.

See also: [3PCD Breakage Report](https://issuetracker.google.com/issues?q=status:open%20componentid:1306484&s=created_time:desc)s on Google's issue tracker.

2024-07-25 09:48 UTC, devnoname120 commented on docker-compose.yml
>        - WDS_SOCKET_PORT=3000
Unless I missed something, port `3000` isn't exposed in Docker. This means that the frontend cannot connect to this port for hot module reloading.

2024-07-25 09:48 UTC, devnoname120 commented on setup/docker-compose.setup.yml
> +      - "2019:2019" # Caddy Admin API - only necessary for initially trusting its CA certificate.
Did you intend to publicly publish these ports? Docker defaults to `0.0.0.0/0` [even if`ufw` is manually configured to block incoming connections from outside to that port](https://github.com/moby/moby/issues/4737).

```suggestion
    ports:
      - "127.0.0.1:2019:2019" # Caddy Admin API - only necessary for initially trusting its CA certificate.
```

2024-07-25 09:48 UTC, devnoname120 commented on setup/setup.Caddyfile
> +	# via the "origins" restriction.
The `origin` header can be spoofed (`curl -H 'Origin: http://host.docker.internal' ...`) so unless I missed something it doesn't meaningfully improve security… Let me know if I got this wrong (I'm not a Caddy expert).

2024-07-25 09:48 UTC, devnoname120 commented on setup/setup.sh
> +caddy trust
I recommend running this script through [`shellcheck`](https://www.shellcheck.net/). Here is the output:

```
$ shellcheck myscript
 
[Line 3:](javascript:setPosition(3, 23))
if ! command -v caddy &> /dev/null; then
                      ^-- [SC3020](https://www.shellcheck.net/wiki/SC3020) (warning): In POSIX sh, &> is undefined.
 
[Line 10:](javascript:setPosition(10, 1))
function cleanup {
^-- [SC2113](https://www.shellcheck.net/wiki/SC2113) (warning): 'function' keyword is non-standard. Use 'foo()' instead of 'function foo'.
 
[Line 11:](javascript:setPosition(11, 47))
    docker compose -f ./docker-compose.yml -f $here/docker-compose.setup.yml down setup > /dev/null
                                              ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([2])), apply [all SC2086](javascript:applyFixCode(2086)))
    docker compose -f ./docker-compose.yml -f "$here"/docker-compose.setup.yml down setup > /dev/null
 
[Line 15:](javascript:setPosition(15, 43))
docker compose -f ./docker-compose.yml -f $here/docker-compose.setup.yml up -d setup > /dev/null
                                          ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([3])), apply [all SC2086](javascript:applyFixCode(2086)))
docker compose -f ./docker-compose.yml -f "$here"/docker-compose.setup.yml up -d setup > /dev/null
```

Here is a fixed version of the script:

```suggestion
#!/bin/sh

if ! command -v caddy > /dev/null 2>&1; then
  echo "Error: 'caddy' not found in PATH. Please install caddy before running this script, e.g. via chocolatey."
  exit 1
fi

here=$(dirname "$0")

cleanup() {
    docker compose -f ./docker-compose.yml -f "$here"/docker-compose.setup.yml down setup > /dev/null
}
trap cleanup EXIT

docker compose -f ./docker-compose.yml -f "$here"/docker-compose.setup.yml up -d setup > /dev/null

caddy trust
```

2024-07-25 11:17 UTC, RudolfSchreier commented on setup/setup.Caddyfile
> +	# via the "origins" restriction.
To clarify, this comment means to express "Here is the best way I could get caddy to have any restrictions whatsoever.", not "I used the Origin header as a restriction because it's the best method I could find".

I think when I implemented this, I could find no better option. There might have been a reason why I so broadly opened this port to `0.0.0.0`, but I cannot remember what that would have been - possibly DNS-related.

2024-07-25 11:20 UTC, RudolfSchreier requested changes
I added some comments to @devnoname120's comments on security, which I agree with!

I know this is just a fun local example - but the code is very reuse-worthy, so I want to make sure we get it right, and use the opportunity to learn more about some Docker networking footguns 😊.

2024-07-25 12:39 UTC, roosnic1 commented on README.md
> +3. Select `Allow all cookies` or `Allow third-party cookies`
This code comes from #1 and will be edited there.

2024-07-25 12:39 UTC, roosnic1 commented on docker-compose.yml
>        - WDS_SOCKET_PORT=3000
This code comes from https://github.com/swisstxt/stxt-auth/pull/1 and will be edited there.

2024-07-25 12:40 UTC, roosnic1 commented on setup/docker-compose.setup.yml
> +      - "2019:2019" # Caddy Admin API - only necessary for initially trusting its CA certificate.
@RudolfSchreier  and @devnoname120  done and tested. All works. Thanks for the suggestion.

2024-07-25 12:40 UTC, roosnic1 commented on setup/setup.sh
> +caddy trust
@devnoname120 done and thanks.

2024-07-25 13:24 UTC, RudolfSchreier commented on setup/docker-compose.setup.yml
> +      - "2019:2019" # Caddy Admin API - only necessary for initially trusting its CA certificate.
Just caught up with @roosnic1 via Teams - this change is actually in #3, but he will merge both after one another, so this is fine :).

2024-07-25 13:24 UTC, RudolfSchreier approved these changes
👍

2024-07-25 13:38 UTC, devnoname120 commented on README.md
> +3. Select `Allow all cookies` or `Allow third-party cookies`
@roosnic1 Should this comment be moved to the mentioned PR or do you have something else in mind?

2024-07-25 15:00 UTC, devnoname120 commented on README.md
> +3. Select `Allow all cookies` or `Allow third-party cookies`
Ah ok, I don't have all the context but as long as the third-party cookies deprecation situation is known and accounted for then LGTM

2024-07-25 15:00 UTC, devnoname120 approved these changes

2024-07-25 16:52 UTC, swisstxtsokol approved these changes
Wanted to comment the npm command in Readme, but Rudorf already commented. The rest is fine

2024-07-25 18:02 UTC, merged