reuse the same code for the applications
swisstxt/stxt-auth pull request #3
Opened 2024-07-20 13:48 UTC by roosnic1

This PR cleans up the code for the client application. It reuses the same code for multiple applications and introduces a few environment variables to simulate differences between the applications.

The first commit again has the changes of renaming the directories and doesn't need to be reviewed.

2024-07-24 07:29 UTC, roosnic1 commented on example-client/Dockerfile
> +COPY . .
@RudolfSchreier because we use npm workspaces the `node_modules` should only exist in the root directory. But i added it now to the `.dockerignore` to be double sure 😄.

2024-07-24 07:49 UTC, roosnic1 commented on example-client/Dockerfile
> +RUN npm install
`npm clean-install` only works with an existing `package-lock.json` and since we are using npm workspaces that file is in the root directory. Accessing files outside the docker context is very hard 🙃. Long story short. Since this is an example app that will never be used in production, i went for `npm install`.

2024-07-25 09:57 UTC, devnoname120 approved these changes
LGTM 👌

2024-07-25 09:57 UTC, devnoname120 commented on example-client/package.json
> +    "start": "HOST=0.0.0.0 PORT=3000 react-scripts start",
For my own understanding, why is setting the `HOST` to `0.0.0.0` rather than `127.0.0.1` knowing that it's behind a reverse proxy?

2024-07-25 11:28 UTC, RudolfSchreier approved these changes
LGTM! 💃

2024-07-25 16:50 UTC, swisstxtsokol commented
Could you please remove this issue from the Readme?
`The package `shared` has to be linked to the `app1/client` and `app1/client` and imported to `index.js` in both applications.`

2024-07-25 16:50 UTC, swisstxtsokol requested changes

2024-07-25 16:50 UTC, swisstxtsokol commented on example-client/Dockerfile
> +RUN npm install
We have to leave `npm config set strict-ssl false && npm install` on Windows

2024-07-25 18:01 UTC, merged