Activate scripts in the admin panel
swisstxt/stxt-auth pull request #4
Opened 2024-07-29 07:31 UTC by swisstxtsokol

I need it in order to add a short script that adds a new user to some group by default.
Otherwise a new user from Active Directory will get an error page after the first login.

2024-07-29 12:28 UTC, roosnic1 requested changes

2024-07-29 12:28 UTC, roosnic1 commented on Dockerfile
> +ENV KC_FEATURES=script
I think on this line the ENV var doesn't have any affet. If it's needed in the build it should be before line 11 and if it's need during runtime it should be after the `FROM base`.

2024-07-30 14:23 UTC, roosnic1 approved these changes
🎉

2024-07-30 15:19 UTC, devnoname120 approved these changes

2024-07-31 12:19 UTC, merged